version: '3.1'

services: 
  app-db: 
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - './mongodbdata:/data'
  
  app-parse-server:
    image: parseplatform/parse-server
    ports: 
      - 1337:1337
    depends_on:
      - app-db
    environment:
      - PARSE_SERVER_APPLICATION_ID=YOUR_APP_ID
      - PARSE_SERVER_MASTER_KEY=YOUR_APP_KEY
      - VERBOSE=0
      - PARSE_SERVER_DATABASE_URI=mongodb://app-db:27017/test      
  
  app-parse-dashboard:
    image: parseplatform/parse-dashboard
    ports:
      - 8080:4040  
    depends_on:
      - app-parse-server
    environment:
        - PARSE_DASHBOARD_SERVER_URL=http://localhost:1337/parse
        - PARSE_DASHBOARD_ALLOW_INSECURE_HTTP=1
        - PARSE_DASHBOARD_APP_ID=YOUR_APP_ID
        - PARSE_DASHBOARD_MASTER_KEY=YOUR_APP_KEY
        - PARSE_DASHBOARD_USER_ID=YOUR_USER
        - PARSE_DASHBOARD_USER_PASSWORD=YOUR_PASS